---
# tasks file for users

#- name: Create group devops
#  ansible.builtin.group:
#    name: devops
#    state: present

#- name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
#  ansible.builtin.user:
#    name: "{{ item }}"
#    state: present
#    group: devops
#  loop:
#    - john
#    - jarade
#    - alex
#    - rena

- name: create ansible user
  ansible.builtin.user:
    name: ansible
    state: present
    groups: wheel
    append: yes
    password: "{{user_pass | password_hash('sha512')}}"

...
